### 
POST http://localhost:8001/face/profile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="user_id"
Content-Type: text/plain

2
--WebAppBoundary
Content-Disposition: form-data; name="profile_photo"
Content-Type: text/plain

true
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="face.jpeg"
Content-Type: image/jpeg

< ./face.jpeg
--WebAppBoundary--



###
POST http://localhost:8001/face/profile?user_id=1&profile_photo=true
Content-Type: multipart/form-data; charset=utf-8

--boundary
Content-Disposition: form-data; name="file"; filename="profile.jpg"
Content-Type: image/jpeg

< ./face.jpeg
--boundary--

###
POST http://localhost:8001/face/profile?user_id=2&profile_photo=false
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="face.jpeg"
Content-Type: image/jpeg

< ./face.jpeg
--WebAppBoundary--




###
POST http://127.0.0.1:8001/face/enroll
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="user_id"

2

--boundary123
Content-Disposition: form-data; name="file"; filename="test_image.jpg"
Content-Type: image/jpeg

< ../insightface/images/Morgan_Freeman/freeman_1.jpeg
--boundary123--


###
POST http://127.0.0.1:8001/face/recognize
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="file"; filename="test_image.jpg"
Content-Type: image/jpeg

< ../insightface/images/Morgan_Freeman/freeman_6.jpeg
--boundary123--
###